### ISSUE TITLE
Trouble on Setting it Up.

### ISSUE THREAD

**Issue by dannieltung** [ConvertKit/instagram_basic_display#8]
Hey there! Really sorry for any dumb question but Im a rookie on this area....
Im trying to set things up but have no idea where should I implement this part ot the code:
```
client = InstagramBasicDisplay::Client.new
user = User.first

long_token_request = client.long_lived_token(short_lived_token: user.instagram_token)

if long_token_request.success?
  auth_token = token_request.payload.access_token
  expires_in = token_request.payload.expires_in
  user.update_instagram_token(token: token, expires_in: expires_in)
else
  render json: long_token_request.error, status: 400
end
```

Should I code it on my def home inside PagesController?
Im coding a simple landing page where Im supposed to render my client's instagram feed....Thank you so much in advance!

**Comment by raquelxmoss** [comment]
Hey @dannieltung, thanks for the question. You can certainly put that inside your controller action as a jumping off point. How you organise the code in your application is largely up to you, but should be informed by Rails principles. I'd recommending diving in a bit more to the Rails Guides to help you make a decision on how to organise things.  

In the meantime, put it in your controller and do some experimenting, it might become more clear to you as you build out your app.
